name: "Reviewer Roulette"

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  example_assign_reviews:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      
    name: An example job to assign reviewers
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assign random reviewers to PR
        uses: ihs7/action-reviewer-roulette@v1
        with:
          number-of-reviewers: 1
